replacing-seed: 123456789

Swap-Shortcut:
  # F/Q快捷键冷却
  cooldown: 500 # ms
  # Shift+F
  whenSneakF: ''
  # 低头时F
  whenLookDownF: ''
  # 抬头时F
  whenLookUpF: ''
  # Shift+Q
  whenSneakQ: ''
  # 低头时Q
  whenLookDownQ: ''
  # 抬头时Q
  whenLookUpQ: ''

ResourcePack:
  - id: ''
    # 资源包url
    url: ''
    # 资源包hash 如果不用验证保持默认即可
    hash: ''
    # 资源包成功加载后动作
    onLoaded: [ ]
    # 拒绝资源包后动作
    onDeclined:
      - 'command inline "kick {{ sender }} §7请将服务器资源包设置为§f§n启用" as console' # 踢出玩家
    # 接受资源包后动作
    onAccepted: [ ]
    # 资源包下载失败时动作
    onFailedDownload:
      - 'tell "§c资源包下载失败!"'
    # 资源包移除时动作
    onRemoved: [ ]