replacing_seed: 123456789

# 快捷键
shortcuts:
  # F/Q快捷键冷却
  cooldown: 500 # ms
  # Shift+F
  sneak_swap: [ ]
  # 低头时F
  down_swap: [ ]
  # 抬头时F
  up_swap: [ ]
  # Shift+Q
  sneak_drop: [ ]
  # 低头时Q
  down_drop: [ ]
  # 抬头时Q
  up_drop: [ ]

# 上传资源包
automatically_upload:
  cos:
    secret_id: ~
    secret_key: ~
    region: ~
    bucket: ~
    key: 'pack.zip'

# 资源包管理
resource_packs:
  empty:
    # 资源包url
    url: 'http://cdn.moep.tv/files/Empty.zip'
    # 资源包hash 如果不用验证保持~即可
    hash: '01517226212d27586ea0c5d6aff1aa5492dd2484'
    # 使用资源包条件
    condition: ~
    # 资源包成功加载后动作
    loaded: [ ]
    # 拒绝资源包后动作
    declined:
      - 'command inline "kick {{ sender }} §7请将服务器资源包设置为§f§n启用" as console' # 踢出玩家
    # 资源包下载失败时动作
    failed:
      - 'tell "§c资源包下载失败!"'
    # 接受资源包后动作
    accepted: [ ]
    # 资源包移除时动作
    removed: [ ]